// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace DcmsMobile.REQ2.Areas.REQ2.Controllers {
    public partial class AutoCompleteController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected AutoCompleteController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult SkuAutocomplete() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.SkuAutocomplete);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public AutoCompleteController Actions { get { return MVC_REQ2.REQ2.AutoComplete; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "REQ2";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "AutoComplete";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "AutoComplete";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string SkuAutocomplete = "SkuAutocomplete";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string SkuAutocomplete = "SkuAutocomplete";
        }


        static readonly ActionParamsClass_SkuAutocomplete s_params_SkuAutocomplete = new ActionParamsClass_SkuAutocomplete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SkuAutocomplete SkuAutocompleteParams { get { return s_params_SkuAutocomplete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SkuAutocomplete {
            public readonly string term = "term";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_AutoCompleteController: DcmsMobile.REQ2.Areas.REQ2.Controllers.AutoCompleteController {
        public T4MVC_AutoCompleteController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult SkuAutocomplete(string term) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.SkuAutocomplete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
