// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace DcmsMobile.DcmsLite.Areas.DcmsLite.Controllers {
    public partial class ValidationController {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ValidationController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ValidationController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result) {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ValidateBox() {
            return new T4MVC_ActionResult(Area, Name, ActionNames.ValidateBox);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ValidationController Actions { get { return MVC_DcmsLite.DcmsLite.Validation; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "DcmsLite";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Validation";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Validation";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass {
            public readonly string Index = "Index";
            public readonly string ValidateBox = "ValidateBox";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants {
            public const string Index = "Index";
            public const string ValidateBox = "ValidateBox";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index {
            public readonly string lastScan = "lastScan";
            public readonly string sound = "sound";
        }
        static readonly ActionParamsClass_ValidateBox s_params_ValidateBox = new ActionParamsClass_ValidateBox();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ValidateBox ValidateBoxParams { get { return s_params_ValidateBox; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ValidateBox {
            public readonly string model = "model";
        }
        static readonly ViewNames s_views = new ViewNames();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewNames Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewNames {
            public readonly string Index = "Index";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ValidationController: DcmsMobile.DcmsLite.Areas.DcmsLite.Controllers.ValidationController {
        public T4MVC_ValidationController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Index(string lastScan, char sound) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "lastScan", lastScan);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sound", sound);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ValidateBox(DcmsMobile.DcmsLite.ViewModels.Validation.IndexViewModel model) {
            var callInfo = new T4MVC_ActionResult(Area, Name, ActionNames.ValidateBox);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
