// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Shipping
{
    public class ContentController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string GuidedTruckLoading = "GuidedTruckLoading";
            }
            public readonly string GuidedTruckLoading = "~/Areas/Shipping/Content/GuidedTruckLoading.ppt";
            static readonly _imagesClass s_images = new _imagesClass();
            public _imagesClass images { get { return s_images; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _imagesClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string a1 = "a1";
                    public readonly string ajax_loader = "ajax-loader";
                    public readonly string calendar = "calendar";
                }
                public readonly string a1 = "~/Areas/Shipping/Content/images/a1.gif";
                public readonly string ajax_loader = "~/Areas/Shipping/Content/images/ajax-loader.gif";
                public readonly string calendar = "~/Areas/Shipping/Content/images/calendar.gif";
            }
            static readonly _SoundsClass s_Sounds = new _SoundsClass();
            public _SoundsClass Sounds { get { return s_Sounds; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _SoundsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string Error = "Error";
                    public readonly string success = "success";
                    public readonly string warning = "warning";
                }
                public readonly string Error = "~/Areas/Shipping/Content/Sounds/Error.wav";
                public readonly string success = "~/Areas/Shipping/Content/Sounds/success.wav";
                public readonly string warning = "~/Areas/Shipping/Content/Sounds/warning.wav";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
