// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace DcmsMobile.Receiving.Areas.Receiving.Controllers
{
    public partial class RadController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RadController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetSpotCheckPercentage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetSpotCheckPercentage);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteSpotCheckPercentage()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteSpotCheckPercentage);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RadController Actions { get { return MVC_Receiving.Receiving.Rad; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Receiving";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Rad";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Rad";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string SetSpotCheckPercentage = "SetSpotCheckPercentage";
            public readonly string DeleteSpotCheckPercentage = "DeleteSpotCheckPercentage";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string SetSpotCheckPercentage = "SetSpotCheckPercentage";
            public const string DeleteSpotCheckPercentage = "DeleteSpotCheckPercentage";
        }


        static readonly ActionParamsClass_SetSpotCheckPercentage s_params_SetSpotCheckPercentage = new ActionParamsClass_SetSpotCheckPercentage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetSpotCheckPercentage SetSpotCheckPercentageParams { get { return s_params_SetSpotCheckPercentage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetSpotCheckPercentage
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DeleteSpotCheckPercentage s_params_DeleteSpotCheckPercentage = new ActionParamsClass_DeleteSpotCheckPercentage();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteSpotCheckPercentage DeleteSpotCheckPercentageParams { get { return s_params_DeleteSpotCheckPercentage; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteSpotCheckPercentage
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _addSpotCheckPartial = "_addSpotCheckPartial";
                public readonly string _editSpotCheckPartial = "_editSpotCheckPartial";
                public readonly string _spotCheckListPartial = "_spotCheckListPartial";
                public readonly string Index = "Index";
            }
            public readonly string _addSpotCheckPartial = "~/Areas/Receiving/Rad/_addSpotCheckPartial.cshtml";
            public readonly string _editSpotCheckPartial = "~/Areas/Receiving/Rad/_editSpotCheckPartial.cshtml";
            public readonly string _spotCheckListPartial = "~/Areas/Receiving/Rad/_spotCheckListPartial.cshtml";
            public readonly string Index = "~/Areas/Receiving/Rad/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_RadController : DcmsMobile.Receiving.Areas.Receiving.Controllers.RadController
    {
        public T4MVC_RadController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SetSpotCheckPercentageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, DcmsMobile.Receiving.ViewModels.Rad.SpotCheckViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetSpotCheckPercentage(DcmsMobile.Receiving.ViewModels.Rad.SpotCheckViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetSpotCheckPercentage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SetSpotCheckPercentageOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void DeleteSpotCheckPercentageOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, DcmsMobile.Receiving.ViewModels.Rad.SpotCheckViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteSpotCheckPercentage(DcmsMobile.Receiving.ViewModels.Rad.SpotCheckViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteSpotCheckPercentage);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            DeleteSpotCheckPercentageOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
