// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
#pragma warning disable 1591, 3008, 3009
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace DcmsMobile.Inquiry.Areas.Inquiry.ShipmentEntity
{
    public partial class ShipmentEntityController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShipmentEntityController() { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ShipmentEntityController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult OutboundShipment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OutboundShipment);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintBol()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintBol);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MasterBol()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MasterBol);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MasterBolExcel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MasterBolExcel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PrintMasterBol()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintMasterBol);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult OutboundShipmentExcel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OutboundShipmentExcel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Appointment()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Appointment);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShipmentEntityController Actions { get { return MVC_Inquiry.Inquiry.ShipmentEntity; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Inquiry";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ShipmentEntity";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ShipmentEntity";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string OutboundShipment = "OutboundShipment";
            public readonly string PrintBol = "PrintBol";
            public readonly string MasterBol = "MasterBol";
            public readonly string MasterBolExcel = "MasterBolExcel";
            public readonly string PrintMasterBol = "PrintMasterBol";
            public readonly string OutboundShipmentExcel = "OutboundShipmentExcel";
            public readonly string Appointment = "Appointment";
            public readonly string ParentShipmentList = "ParentShipmentList";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string OutboundShipment = "OutboundShipment";
            public const string PrintBol = "PrintBol";
            public const string MasterBol = "MasterBol";
            public const string MasterBolExcel = "MasterBolExcel";
            public const string PrintMasterBol = "PrintMasterBol";
            public const string OutboundShipmentExcel = "OutboundShipmentExcel";
            public const string Appointment = "Appointment";
            public const string ParentShipmentList = "ParentShipmentList";
        }


        static readonly ActionParamsClass_OutboundShipment s_params_OutboundShipment = new ActionParamsClass_OutboundShipment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OutboundShipment OutboundShipmentParams { get { return s_params_OutboundShipment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OutboundShipment
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PrintBol s_params_PrintBol = new ActionParamsClass_PrintBol();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintBol PrintBolParams { get { return s_params_PrintBol; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintBol
        {
            public readonly string parentShippingId = "parentShippingId";
            public readonly string printerId = "printerId";
        }
        static readonly ActionParamsClass_MasterBol s_params_MasterBol = new ActionParamsClass_MasterBol();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MasterBol MasterBolParams { get { return s_params_MasterBol; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MasterBol
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_MasterBolExcel s_params_MasterBolExcel = new ActionParamsClass_MasterBolExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MasterBolExcel MasterBolExcelParams { get { return s_params_MasterBolExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MasterBolExcel
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PrintMasterBol s_params_PrintMasterBol = new ActionParamsClass_PrintMasterBol();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PrintMasterBol PrintMasterBolParams { get { return s_params_PrintMasterBol; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PrintMasterBol
        {
            public readonly string address = "address";
            public readonly string city = "city";
            public readonly string state = "state";
            public readonly string zipcode = "zipcode";
            public readonly string country = "country";
            public readonly string mBolId = "mBolId";
            public readonly string printerId = "printerId";
        }
        static readonly ActionParamsClass_OutboundShipmentExcel s_params_OutboundShipmentExcel = new ActionParamsClass_OutboundShipmentExcel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_OutboundShipmentExcel OutboundShipmentExcelParams { get { return s_params_OutboundShipmentExcel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_OutboundShipmentExcel
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Appointment s_params_Appointment = new ActionParamsClass_Appointment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Appointment AppointmentParams { get { return s_params_Appointment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Appointment
        {
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Appointment = "Appointment";
                public readonly string MasterBol = "MasterBol";
                public readonly string ParentShipment = "ParentShipment";
                public readonly string ParentShipmentList = "ParentShipmentList";
            }
            public readonly string Appointment = "~/Areas/Inquiry/ShipmentEntity/Appointment.cshtml";
            public readonly string MasterBol = "~/Areas/Inquiry/ShipmentEntity/MasterBol.cshtml";
            public readonly string ParentShipment = "~/Areas/Inquiry/ShipmentEntity/ParentShipment.cshtml";
            public readonly string ParentShipmentList = "~/Areas/Inquiry/ShipmentEntity/ParentShipmentList.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ShipmentEntityController : DcmsMobile.Inquiry.Areas.Inquiry.ShipmentEntity.ShipmentEntityController
    {
        public T4MVC_ShipmentEntityController() : base(Dummy.Instance) { }

        [NonAction]
        partial void OutboundShipmentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult OutboundShipment(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OutboundShipment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            OutboundShipmentOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PrintBolOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string parentShippingId, string printerId);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintBol(string parentShippingId, string printerId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintBol);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentShippingId", parentShippingId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "printerId", printerId);
            PrintBolOverride(callInfo, parentShippingId, printerId);
            return callInfo;
        }

        [NonAction]
        partial void MasterBolOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult MasterBol(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MasterBol);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            MasterBolOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void MasterBolExcelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult MasterBolExcel(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MasterBolExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            MasterBolExcelOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void PrintMasterBolOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string address, string city, string state, string zipcode, string country, string mBolId, string printerId);

        [NonAction]
        public override System.Web.Mvc.ActionResult PrintMasterBol(string address, string city, string state, string zipcode, string country, string mBolId, string printerId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PrintMasterBol);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "address", address);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "city", city);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "state", state);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "zipcode", zipcode);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "country", country);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "mBolId", mBolId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "printerId", printerId);
            PrintMasterBolOverride(callInfo, address, city, state, zipcode, country, mBolId, printerId);
            return callInfo;
        }

        [NonAction]
        partial void OutboundShipmentExcelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Web.Mvc.ActionResult OutboundShipmentExcel(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.OutboundShipmentExcel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            OutboundShipmentExcelOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AppointmentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult Appointment(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Appointment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            AppointmentOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void ParentShipmentListOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ParentShipmentList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ParentShipmentList);
            ParentShipmentListOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009
