// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public static class MVC_BoxPick {
    static readonly BoxPickClass s_BoxPick = new BoxPickClass();
    public static BoxPickClass BoxPick { get { return s_BoxPick; } }
}

namespace T4MVC {
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class BoxPickClass {
        public readonly string Name = "BoxPick";
        public DcmsMobile.BoxPick.Areas.BoxPick.Controllers.ConfirmController Confirm = new DcmsMobile.BoxPick.Areas.BoxPick.Controllers.T4MVC_ConfirmController();
        public DcmsMobile.BoxPick.Areas.BoxPick.Controllers.HelpController Help = new DcmsMobile.BoxPick.Areas.BoxPick.Controllers.T4MVC_HelpController();
        public DcmsMobile.BoxPick.Areas.BoxPick.Controllers.HomeController Home = new DcmsMobile.BoxPick.Areas.BoxPick.Controllers.T4MVC_HomeController();
        public DcmsMobile.BoxPick.Areas.BoxPick.Controllers.MainContentController MainContent = new DcmsMobile.BoxPick.Areas.BoxPick.Controllers.T4MVC_MainContentController();
        public T4MVC.BoxPick.SharedController Shared = new T4MVC.BoxPick.SharedController();
    }
}

  

  

[GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
public class T4MVC_ActionResult : System.Web.Mvc.ActionResult, IT4MVCActionResult {
    public T4MVC_ActionResult(string area, string controller, string action, string protocol = null): base()  {
        this.InitMVCT4Result(area, controller, action, protocol);
    }
     
    public override void ExecuteResult(System.Web.Mvc.ControllerContext context) { }
    
    public string Controller { get; set; }
    public string Action { get; set; }
    public string Protocol { get; set; }
    public RouteValueDictionary RouteValueDictionary { get; set; }
}



namespace Links_BoxPick {
    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Scripts {
        private const string URLPATH = "~/Scripts";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        public static readonly string jquery_1_8_2_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-1.8.2.min.js") ? Url("jquery-1.8.2.min.js") : Url("jquery-1.8.2.js");
                      
        public static readonly string jquery_ui_1_10_0_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery-ui-1.10.0.min.js") ? Url("jquery-ui-1.10.0.min.js") : Url("jquery-ui-1.10.0.js");
                      
        public static readonly string jquery_validate_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.min.js") ? Url("jquery.validate.min.js") : Url("jquery.validate.js");
                      
        public static readonly string jquery_validate_unobtrusive_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/jquery.validate.unobtrusive.min.js") ? Url("jquery.validate.unobtrusive.min.js") : Url("jquery.validate.unobtrusive.js");
                      
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Content {
        private const string URLPATH = "~/Content";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class themes {
            private const string URLPATH = "~/Content/themes";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Start1_10_0 {
                private const string URLPATH = "~/Content/themes/Start1.10.0";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class images {
                    private const string URLPATH = "~/Content/themes/Start1.10.0/images";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                }
            
                public static readonly string jquery_ui_min_css = Url("jquery-ui.min.css");
            }
        
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static class Areas {
        private const string URLPATH = "~/Areas";
        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static class BoxPick {
            private const string URLPATH = "~/Areas/BoxPick";
            public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
            public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Content {
                private const string URLPATH = "~/Areas/BoxPick/Content";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string BoxPick_all_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/BoxPick-all.min.css") ? Url("BoxPick-all.min.css") : Url("BoxPick-all.css");
                     
                public static readonly string BoxPick_all_min_css = Url("BoxPick-all.min.css");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Sounds {
                    private const string URLPATH = "~/Areas/BoxPick/Content/Sounds";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string BoxComplete_wav = Url("BoxComplete.wav");
                    public static readonly string Error_wav = Url("Error.wav");
                    public static readonly string success_wav = Url("success.wav");
                    public static readonly string warning_wav = Url("warning.wav");
                }
            
                public static readonly string standardized_css = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/standardized.min.css") ? Url("standardized.min.css") : Url("standardized.css");
                     
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Controllers {
                private const string URLPATH = "~/Areas/BoxPick/Controllers";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Scripts {
                private const string URLPATH = "~/Areas/BoxPick/Scripts";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string BoxPick_all_js = T4MVCHelpers.IsProduction() && T4Extensions.FileExists(URLPATH + "/BoxPick-all.min.js") ? Url("BoxPick-all.min.js") : Url("BoxPick-all.js");
                              
            }
        
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public static class Views {
                private const string URLPATH = "~/Areas/BoxPick/Views";
                public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                public static readonly string _ViewStart_cshtml = Url("_ViewStart.cshtml");
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Confirm {
                    private const string URLPATH = "~/Areas/BoxPick/Views/Confirm";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string ADRPallet_cshtml = Url("ADRPallet.cshtml");
                    public static readonly string ConfirmSuspenseCarton_cshtml = Url("ConfirmSuspenseCarton.cshtml");
                    public static readonly string PartialPickPallet_cshtml = Url("PartialPickPallet.cshtml");
                    public static readonly string Print_cshtml = Url("Print.cshtml");
                    public static readonly string SkipUcc_cshtml = Url("SkipUcc.cshtml");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Help {
                    private const string URLPATH = "~/Areas/BoxPick/Views/Help";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string CartonHelp_cshtml = Url("CartonHelp.cshtml");
                    public static readonly string PalletHelp_cshtml = Url("PalletHelp.cshtml");
                    public static readonly string PartialPickPalletHelp_cshtml = Url("PartialPickPalletHelp.cshtml");
                    public static readonly string SkipUccHelp_cshtml = Url("SkipUccHelp.cshtml");
                    public static readonly string UccHelp_cshtml = Url("UccHelp.cshtml");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Home {
                    private const string URLPATH = "~/Areas/BoxPick/Views/Home";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string Building_cshtml = Url("Building.cshtml");
                    public static readonly string Carton_cshtml = Url("Carton.cshtml");
                    public static readonly string Pallet_cshtml = Url("Pallet.cshtml");
                    public static readonly string Ucc_cshtml = Url("Ucc.cshtml");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class MainContent {
                    private const string URLPATH = "~/Areas/BoxPick/Views/MainContent";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _buildingPartial_cshtml = Url("_buildingPartial.cshtml");
                    public static readonly string _cartonPartial_cshtml = Url("_cartonPartial.cshtml");
                }
            
                [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                public static class Shared {
                    private const string URLPATH = "~/Areas/BoxPick/Views/Shared";
                    public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                    public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                    public static readonly string _bottomPartial_cshtml = Url("_bottomPartial.cshtml");
                    public static readonly string _BoxList_cshtml = Url("_BoxList.cshtml");
                    public static readonly string _layoutBoxPick_cshtml = Url("_layoutBoxPick.cshtml");
                    public static readonly string _layoutBoxPick_mobile_cshtml = Url("_layoutBoxPick.mobile.cshtml");
                    public static readonly string _PalletStatus_cshtml = Url("_PalletStatus.cshtml");
                    public static readonly string _soundPartial_cshtml = Url("_soundPartial.cshtml");
                    public static readonly string _tabsPartial_cshtml = Url("_tabsPartial.cshtml");
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class DisplayTemplates {
                        private const string URLPATH = "~/Areas/BoxPick/Views/Shared/DisplayTemplates";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string ValueWithShortName_cshtml = Url("ValueWithShortName.cshtml");
                    }
                
                    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
                    public static class EditorTemplates {
                        private const string URLPATH = "~/Areas/BoxPick/Views/Shared/EditorTemplates";
                        public static string Url() { return T4MVCHelpers.ProcessVirtualPath(URLPATH); }
                        public static string Url(string fileName) { return T4MVCHelpers.ProcessVirtualPath(URLPATH + "/" + fileName); }
                        public static readonly string scan_cshtml = Url("scan.cshtml");
                    }
                
                }
            
            }
        
        }
    
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public static partial class bundles {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class scripts {}
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public static partial class styles {}
    }
}





#endregion T4MVC
#pragma warning restore 1591


